### ISSUE TITLE
Question about normalized_driving_line

### ISSUE THREAD

**Issue by mgagvani** [MatthewCash/libforza#1]
Hello, 

What does the `normalized_driving_line` variable in [ForzaTelemetry.h](https://github.com/MatthewCash/libforza/blob/cac2b2e80b84e012f7a5154a04bb000b074f06f3/src/ForzaTelemetry.h#L92) represent? I did some empirical testing but wasn't able to discern what it correlates to. Any input would be greatly appreciated.

**Comment by MatthewCash** [comment]
I haven't been able to figure out what it represents either. The official [forum post](https://forums.forzamotorsport.net/turn10_postst128499_Forza-Motorsport-7--Data-Out--feature-details.aspx) outlining the data structure gives no mention of its purpose. Sorry I can't be of any help regarding this, I wish the developers were more clear about their intentions and plans for the Data Out feature.

I'm going to close the issue because I don't think I will be able with this. I can let you know if I find any more information though.

**Comment by robominds** [comment]
I did some empirical testing on normalized_driving_line and found that +127 seemed to correlate well with the left edge of the track and -127 correlated well with the right edge of the track. I did not find a correlation with the blue/yellow/red driving line.

This project was just what I was looking for, Thanks!

**Comment by mgagvani** [comment]
@robominds Just curious, what game did you test on specifically?

**Comment by robominds** [comment]
I was testing it with FM7 (version 1.174.4791.0) on an XBox One S.
